package com.zxl.hazel.demo.ds.proxy;    // ==================== Connection 代理 ====================

import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;
import lombok.extern.slf4j.Slf4j;

import java.sql.*;

@Slf4j
@RequiredArgsConstructor
public class TraceConnection implements Connection {




    @Delegate
    private final Connection target;

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql, autoGeneratedKeys), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql, resultSetType, resultSetConcurrency), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql, columnIndexes), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return new TracePreparedStatement(target.prepareStatement(sql, columnNames), sql);
    }

    @Override
    public Statement createStatement() throws SQLException {
        return target.createStatement();
    }
}

